version: '3.4'

services:
  finalproject:
    image: finalproject
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    volumes:
       - .:/usr/src/app

volumes:
    data:
